/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hexin_ai_jni_TalkingFace */

#ifndef _Included_com_hexin_ai_jni_TalkingFace
#define _Included_com_hexin_ai_jni_TalkingFace
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_hexin_ai_jni_TalkingFace_sayHello
  (JNIEnv *, jobject);

// 多实例管理
JNIEXPORT jlong JNICALL Java_com_hexin_ai_jni_TalkingFace_nativeCreate
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_hexin_ai_jni_TalkingFace_nativeDestroy
  (JNIEnv *, jobject, jlong);

JNIEXPORT jboolean JNICALL Java_com_hexin_ai_jni_TalkingFace_init
  (JNIEnv *, jobject, jlong, jint, jint, jint, jstring);

JNIEXPORT jstring JNICALL Java_com_hexin_ai_jni_TalkingFace_process
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring);

JNIEXPORT jstring JNICALL Java_com_hexin_ai_jni_TalkingFace_render
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

JNIEXPORT jstring JNICALL Java_com_hexin_ai_jni_TalkingFace_shutup
  (JNIEnv *, jobject, jlong, jstring, jstring, jstring, jstring);

JNIEXPORT jboolean JNICALL Java_com_hexin_ai_jni_TalkingFace_stop
  (JNIEnv *, jobject, jlong);

// 性能测试接口（静态方法）
JNIEXPORT void JNICALL Java_com_hexin_ai_jni_TalkingFace_startPerfTest
  (JNIEnv *, jclass, jint);

JNIEXPORT jlong JNICALL Java_com_hexin_ai_jni_TalkingFace_getPerfFrameCount
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_hexin_ai_jni_TalkingFace_resetPerfCounter
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
