/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hexin_ai_jni_TalkingFace */

#ifndef _Included_com_hexin_ai_jni_TalkingFace
#define _Included_com_hexin_ai_jni_TalkingFace
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hexin_ai_jni_TalkingFace
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_hexin_ai_jni_TalkingFace_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     com_hexin_ai_jni_TalkingFace
 * Method:    init
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_hexin_ai_jni_TalkingFace_init
  (JNIEnv *, jobject, jint, jint, jint, jstring);

// /*
//  * Class:     com_hexin_ai_jni_TalkingFace
//  * Method:    process
//  * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
//  */
JNIEXPORT jstring JNICALL Java_com_hexin_ai_jni_TalkingFace_process
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_hexin_ai_jni_TalkingFace
 * Method:    render
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hexin_ai_jni_TalkingFace_render
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     com_hexin_ai_jni_TalkingFace
 * Method:    shutup
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hexin_ai_jni_TalkingFace_shutup
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     com_hexin_ai_jni_TalkingFace
 * Method:    stop
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_hexin_ai_jni_TalkingFace_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
